#ifndef PERAMETERS_H
#define PERAMETERS_H
#include "IrrWrapper.h"

const float PLAYER_HEIGHT = 1.75f;
const int	RESPAWN_TIME = 3000;
const int	DECREASE_FOOD_TIME = 15000;
const int	STARVING_DAMAGE_TIME = 100;
const int	EAT_FOOD_TIME = 50;
const int	USE_MEDICAL_TIME = 200;


const int ZOMBIE_IDLE_TIME = 200;
const int ZOMBIE_WANDER_TIME = 1000;
const float ZOMBIE_ACCELERATION = 0.005f;
const float ZOMBIE_FRICTION = 0.95f;
const int ZOMBIE_MAX_HEALTH = 100;
const float ZOMBIE_PURSUIT_SPEED = 0.05f;
const float ZOMBIE_WANDER_SPEED = 0.01f;
const int ZOMBIE_DAMAGE = 10;
const float ZOMBIE_AGRO_RANGE = 10.0f;
const int ZOMBIE_ATTACK_DELAY = 10;

const float PROJECTILE_SPEED = 1.0f;
const int PROJECTILE_LIFE = 1000;
const int BULLET_DAMAGE = 25;

const int PLACE_BLOCK_DEALY = 20;
const int EMPTY_HAND_DELAY = 20;

const SColor fogColor(0, 0, 0, 0);

// Instance Bitmasks:
const unsigned int BITMASK_WORLD = 1;
const unsigned int BITMASK_CHARACTER = 2;
const unsigned int BITMASK_ITEM = 4;

enum ItemType
{
    ITEM_TYPE_NONE,
	ITEM_TYPE_ARMOUR,
	ITEM_TYPE_BASE,
	ITEM_TYPE_BLOCK,
	ITEM_TYPE_CONSUMABLE,
	ITEM_TYPE_PROJECTILE_WEAPON,
	ITEM_TYPE_THROWN_WEAPON,
	ITEM_TYPE_MELEE_WEAPON,
	ITEM_TYPE_TOOL,
	ITEM_TYPE_AMMO
};

enum ArmourSlot
{
	HEAD = 0,
	CHEST,
	ARM,
	SHOULDER,
	HAND,
	BACK,
	LEG,
	FEET
};

enum CharacterInstanceTemplateNames
{
	CHARACTER_INSTANCE_TEMPLATE_SOLDIER,
	CHARACTER_INSTANCE_TEMPLATE_WORKER,
	CHARACTER_INSTANCE_TEMPLATE_ZOMBIE,
	CHARACTER_INSTANCE_TEMPLATE_COW
};

enum ProjectileInstanceTemplateNames
{
	PROJECTILE_INSTANCE_BULLET,
	PROJECTILE_INSTANCE_BLOOD,
	PROJECTILE_INSTANCE_DUST
};

enum FactionIDs
{
	FACTION_ID_PLAYER = 0,
	FACTION_ID_ZOMBIE,
	FACTION_ID_COW
};



enum BlockNames
{
	BLOCK_AIR = 0,
	BLOCK_SAND,
	BLOCK_CONCRETE,
	BLOCK_METAL,
	BLOCK_WOOD,
	BLOCK_SCRAP_METAL,
	BLOCK_ASPHALT,
	BLOCK_BRICK,
	BLOCK_GREEN_CONCRETE,
	BLOCK_BLUE_CONCRETE
};
#endif
